import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import {TeacherFrame,SessionSetup} from './TeacherWorkspace.jsx';

const COURSES=[{id:'theo',code:'THEO 301',name:'Theology',students:34},{id:'hist',code:'HIST 210',name:'Church History',students:41},{id:'phil',code:'PHIL 140',name:'Philosophy',students:28}];
const EXAMS=[{id:'a',title:'Midterm — Romans 8–11',course:'THEO 301',course_id:'theo',duration:50,submissions:34,status:'COMPLETED',prompt:'How does Paul develop his account of hope in Romans 8?'},{id:'b',title:'In-class essay — Christology',course:'THEO 301',course_id:'theo',duration:45,submissions:33,status:'COMPLETED',prompt:'Explain the relationship between the two natures of Christ.'},{id:'c',title:'Reformation causes — response',course:'HIST 210',course_id:'hist',duration:40,submissions:41,status:'COMPLETED',prompt:'Discuss two causes of the Reformation.'}];
const STUDENTS=['Alex Morgan','Jordan Ellis','Sam Taylor'];
const SAMPLE='Paul frames hope as patient expectation rather than simple optimism. His argument begins with present suffering, but places it within a wider account of creation’s renewal.\n\nThe contrast matters: hope does not deny what is difficult. It allows the writer to hold suffering and confidence together without pretending that the tension has already disappeared.';
function Demo(){
 const [screen,setScreen]=useState('sessions');const [exams,setExams]=useState(()=>EXAMS.map(e=>({...e})));const [selected,setSelected]=useState(EXAMS[0]);const [draft,setDraft]=useState('');const [answer,setAnswer]=useState('');const [receipt,setReceipt]=useState(false);const [epoch,setEpoch]=useState(0);
 function navigate(s){if(s==='reset'){setExams(EXAMS.map(e=>({...e})));setSelected(EXAMS[0]);setDraft('');setAnswer('');setReceipt(false);setEpoch(v=>v+1);setScreen('sessions');}else setScreen(s);}
 function open(e){setSelected(e);setScreen('session');setReceipt(false);}
 return <TeacherFrame demo active={['session','write'].includes(screen)?'sessions':screen} onNavigate={navigate}>
 {screen==='sessions'&&<SessionSetup key={epoch} demo hasOriginal courses={COURSES} exams={exams} onCourses={()=>setScreen('students')} onOpen={open} onCreate={async payload=>{const qs=payload.questions||[];const e={...payload,prompt:qs.map((q,i)=>qs.length>1?`${i+1}. ${q}`:q).join('\n\n'),id:`demo-${Date.now()}`,submissions:0};setExams(v=>[e,...v]);open(e);}}/>}
 {screen==='overview'&&<><header className="teacher-head"><div className="eyebrow">Professor demonstration</div><h1>Begin with the student’s own writing.</h1><p>A fictional class shows the journey from a supervised booklet to a thoughtful conversation.</p></header><div className="demo-stats">{[['3','Example classes'],['103','Fictional students'],[String(exams.length),'Example sessions']].map(([v,l])=><div key={l} className="teacher-card demo-stat"><strong>{v}</strong>{l}</div>)}</div><div className="teacher-card teacher-list"><h2>A simple teaching workflow</h2><ol><li>1. Set a question and open the booklets.</li><li>2. A student writes and submits their response.</li><li>3. Read the work and consider its context.</li><li>4. With Original enabled, review eligible writing comparisons. A difference is not an accusation.</li></ol><button className="teacher-primary" onClick={()=>navigate('sessions')}>Try a Bluebook session →</button></div></>}
 {screen==='session'&&<><header className="teacher-head"><div className="eyebrow">Example session</div><h1>{selected.title}</h1><p>{selected.course} · {selected.duration} minutes · fictional records</p></header><section className="teacher-card demo-reader"><h2>The question</h2><p style={{whiteSpace:'pre-wrap',margin:'1rem 0'}}>{selected.prompt}</p><button className="teacher-primary" onClick={()=>{setDraft('');setScreen('write');}}>Preview a student’s booklet</button><button className="quiet-button" onClick={()=>navigate('submissions')}>Read example submissions →</button><p className="hint">This demonstration does not invite real students or save an exam to a server.</p></section></>}
 {screen==='write'&&<><header className="teacher-head"><div className="eyebrow">Student preview · demonstration</div><h1>A little room to think.</h1><p>{selected.prompt}</p></header><form className="teacher-card demo-reader" onSubmit={e=>{e.preventDefault();setAnswer(draft);setReceipt(true);setScreen('submissions');}}><div className="question-field"><label htmlFor="demo-answer">Your example response</label><textarea id="demo-answer" value={draft} required onChange={e=>setDraft(e.target.value)} placeholder="Use fictional text only. This response stays in memory and disappears on refresh." style={{minHeight:250}}/></div><p className="hint">No timer enforcement, recording or background saving in this preview.</p><button className="teacher-primary" type="submit">Submit example booklet</button></form></>}
 {screen==='students'&&<><header className="teacher-head"><div className="eyebrow">Example class</div><h1>Every writer starts somewhere.</h1><p>These names and records are fictional. No authorship model has evaluated them.</p></header><section className="teacher-card teacher-list"><h2>THEO 301 · sample of the class</h2><ul>{STUDENTS.map(s=><li key={s}>{s}<span style={{float:'right'}}>Example writing available</span></li>)}</ul><button className="quiet-button" onClick={()=>navigate('submissions')}>Read a sample booklet →</button></section></>}
 {screen==='submissions'&&<><header className="teacher-head"><div className="eyebrow">Example submission</div><h1>The writing comes first.</h1><p>{receipt?'Your example response is shown below. It has not been saved to a server.':'Alex Morgan · fictional booklet · illustrative prose'}</p></header><section className="teacher-card demo-reader">{receipt&&<p role="status">Example booklet submitted in this preview.</p>}<pre>{answer||SAMPLE}</pre><p className="hint">No detection result or student judgment is attached to this example.</p><button className="quiet-button" onClick={()=>navigate('reports')}>See how a report would be explained →</button></section></>}
 {screen==='reports'&&<><header className="teacher-head"><div className="eyebrow">Illustrative report · not a model result</div><h1>A starting point for conversation.</h1><p>Original’s intended report-only experience explains a comparison and its limits.</p></header><section className="teacher-card teacher-list"><h2>Comparison unavailable in this demonstration</h2><ul><li><strong>Writing context:</strong> ask about the assignment, revision and permitted assistance.</li><li><strong>Baseline:</strong> use only sufficiently long, eligible samples with established provenance.</li><li><strong>Interpretation:</strong> a change in style does not establish why it changed.</li><li><strong>Next step:</strong> review the writing with the student. No automatic accusation or grade decision.</li></ul><button className="teacher-primary" onClick={()=>navigate('sessions')}>Back to Bluebook</button></section></>}
 </TeacherFrame>;
}
createRoot(document.getElementById('root')).render(<Demo/>);
