"""live schema baseline

Fresh alembic baseline for the LIVE pilot schema (WS-6 P2, ADR-006,
docs/AUDIT_2026-07-06.md §10). Creates the 16 tables modeled in
original/db/models/live.py — the SQLAlchemy port of the SQLite DDL from
original/store.py:_get_conn(), with tenancy as a real constraint
(tenant_id FK + composite keys) instead of the "{tenant}:{local}" prefix
convention. The 7 stale v1 revisions are archived in
alembic/versions_v1_archive/ and are not part of this history.

Revision ID: 20128da16c79
Revises:
Create Date: 2026-07-08 10:02:49.140216

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20128da16c79"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("student_id", sa.Text(), nullable=True),
        sa.Column("tenant_id", sa.Text(), nullable=True),
        sa.Column("actor", sa.Text(), nullable=True),
        sa.Column("result", sa.Text(), server_default="ok", nullable=False),
        sa.Column(
            "details_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index("idx_audit_action", "audit_log", ["action", "created_at"], unique=False)
    op.create_index("idx_audit_student", "audit_log", ["student_id", "created_at"], unique=False)
    op.create_table(
        "calibration_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_label", sa.Text(), nullable=True),
        sa.Column("dataset_label", sa.Text(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("auc", sa.Float(), nullable=True),
        sa.Column("n_essays_scored", sa.Integer(), nullable=True),
        sa.Column("n_authors", sa.Integer(), nullable=True),
        sa.Column(
            "config_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "report_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calibration_runs")),
    )
    op.create_index("idx_calibration_started", "calibration_runs", ["started_at"], unique=False)
    op.create_table(
        "tenants",
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("environment", sa.Text(), server_default="demo", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "meta_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("tenant_id", name=op.f("pk_tenants")),
    )
    op.create_index("idx_tenants_environment", "tenants", ["environment"], unique=False)
    op.create_table(
        "tuned_thresholds_v2",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("source_run_id", sa.Integer(), nullable=True),
        sa.Column("no_action", sa.Float(), nullable=False),
        sa.Column("monitor", sa.Float(), nullable=False),
        sa.Column("escalate", sa.Float(), nullable=False),
        sa.Column("verdict_authentic_below", sa.Float(), nullable=True),
        sa.Column("verdict_anomalous_at_or_above", sa.Float(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "provenance_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tuned_thresholds_v2")),
    )
    op.create_index(
        "idx_tuned_thresholds_created", "tuned_thresholds_v2", ["created_at"], unique=False
    )
    op.create_table(
        "ai_likelihood_scores",
        sa.Column("submission_id", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("student_id", sa.Text(), nullable=False),
        sa.Column("probability", sa.Float(), nullable=False),
        sa.Column("band", sa.Text(), nullable=False),
        sa.Column("model_version", sa.Text(), server_default="", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
            name=op.f("fk_ai_likelihood_scores_tenant_id_tenants"),
        ),
        sa.PrimaryKeyConstraint("submission_id", name=op.f("pk_ai_likelihood_scores")),
    )
    op.create_index(
        "idx_ai_likelihood_tenant_student",
        "ai_likelihood_scores",
        ["tenant_id", "student_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "baseline_requests",
        sa.Column("external_request_id", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("student_id", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("requested_at", sa.Float(), nullable=False),
        sa.Column(
            "data_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
            name=op.f("fk_baseline_requests_tenant_id_tenants"),
        ),
        sa.PrimaryKeyConstraint("external_request_id", name=op.f("pk_baseline_requests")),
    )
    op.create_index(
        "idx_baseline_requests_status",
        "baseline_requests",
        ["status", "requested_at"],
        unique=False,
    )
    op.create_table(
        "bluebook_courses",
        sa.Column("course_id", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("code", sa.Text(), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("term", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default="ACTIVE", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.tenant_id"], name=op.f("fk_bluebook_courses_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("course_id", name=op.f("pk_bluebook_courses")),
    )
    op.create_index(
        "idx_bluebook_courses_tenant", "bluebook_courses", ["tenant_id", "created_at"], unique=False
    )
    op.create_table(
        "bluebook_exams",
        sa.Column("exam_id", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("course", sa.Text(), nullable=True),
        sa.Column("duration", sa.Integer(), nullable=True),
        sa.Column("min_words", sa.Integer(), nullable=True),
        sa.Column("max_words", sa.Integer(), nullable=True),
        sa.Column("prompt", sa.Text(), nullable=True),
        sa.Column(
            "conditions_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("status", sa.Text(), server_default="DRAFT", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.tenant_id"], name=op.f("fk_bluebook_exams_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("exam_id", name=op.f("pk_bluebook_exams")),
    )
    op.create_index(
        "idx_bluebook_exams_tenant", "bluebook_exams", ["tenant_id", "created_at"], unique=False
    )
    op.create_table(
        "bluebook_submissions",
        sa.Column("submission_id", sa.Text(), nullable=False),
        sa.Column("exam_id", sa.Text(), nullable=True),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("student_id", sa.Text(), nullable=True),
        sa.Column("candidate", sa.Text(), nullable=True),
        sa.Column("exam_title", sa.Text(), nullable=True),
        sa.Column("course", sa.Text(), nullable=True),
        sa.Column("word_count", sa.Integer(), nullable=True),
        sa.Column("time_min", sa.Integer(), nullable=True),
        sa.Column("stylometric", sa.Integer(), nullable=True),
        sa.Column("ai_score", sa.Integer(), nullable=True),
        sa.Column("status", sa.Text(), server_default="SUBMITTED", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
            name=op.f("fk_bluebook_submissions_tenant_id_tenants"),
        ),
        sa.PrimaryKeyConstraint("submission_id", name=op.f("pk_bluebook_submissions")),
    )
    op.create_index(
        "idx_bluebook_subs_tenant",
        "bluebook_submissions",
        ["tenant_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "corrections",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("submission_id", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=True),
        sa.Column("student_id", sa.Text(), nullable=True),
        sa.Column("original_verdict", sa.Text(), nullable=True),
        sa.Column("original_action", sa.Text(), nullable=True),
        sa.Column("original_divergence_score", sa.Float(), nullable=True),
        sa.Column("corrected_verdict", sa.Text(), nullable=True),
        sa.Column("corrected_action", sa.Text(), nullable=True),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.Column("reviewer", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.tenant_id"], name=op.f("fk_corrections_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_corrections")),
    )
    op.create_index("idx_corrections_created", "corrections", ["created_at"], unique=False)
    op.create_index("idx_corrections_submission", "corrections", ["submission_id"], unique=False)
    op.create_table(
        "fidelity_scores",
        sa.Column("submission_id", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("student_id", sa.Text(), nullable=False),
        sa.Column("fidelity", sa.Float(), nullable=False),
        sa.Column("is_authentic", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.tenant_id"], name=op.f("fk_fidelity_scores_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("submission_id", name=op.f("pk_fidelity_scores")),
    )
    op.create_index(
        "idx_fidelity_tenant_student",
        "fidelity_scores",
        ["tenant_id", "student_id", "is_authentic"],
        unique=False,
    )
    op.create_table(
        "formation_pathways",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("student_id", sa.Text(), nullable=False),
        sa.Column("submission_id", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default="open", nullable=False),
        sa.Column("current_step", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
            name=op.f("fk_formation_pathways_tenant_id_tenants"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_formation_pathways")),
    )
    op.create_index(
        "idx_formation_tenant_student",
        "formation_pathways",
        ["tenant_id", "student_id", "status"],
        unique=False,
    )
    op.create_table(
        "student_names",
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("student_id", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), server_default="", nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.tenant_id"], name=op.f("fk_student_names_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("tenant_id", "student_id", name=op.f("pk_student_names")),
    )
    op.create_table(
        "student_profiles",
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("student_id", sa.Text(), nullable=False),
        sa.Column(
            "data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("rho_bytes", sa.LargeBinary(), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.tenant_id"], name=op.f("fk_student_profiles_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("tenant_id", "student_id", name=op.f("pk_student_profiles")),
    )
    op.create_table(
        "submission_manifests",
        sa.Column("submission_id", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("student_id", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "manifest_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("divergence_score", sa.Float(), nullable=True),
        sa.Column("action", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.tenant_id"],
            name=op.f("fk_submission_manifests_tenant_id_tenants"),
        ),
        sa.PrimaryKeyConstraint("submission_id", name=op.f("pk_submission_manifests")),
    )
    op.create_index(
        "idx_manifest_tenant_student_created",
        "submission_manifests",
        ["tenant_id", "student_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("role", sa.Text(), server_default="professor", nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), server_default="", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.tenant_id"], name=op.f("fk_users_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_index("idx_users_tenant", "users", ["tenant_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_users_tenant", table_name="users")
    op.drop_table("users")
    op.drop_index("idx_manifest_tenant_student_created", table_name="submission_manifests")
    op.drop_table("submission_manifests")
    op.drop_table("student_profiles")
    op.drop_table("student_names")
    op.drop_index("idx_formation_tenant_student", table_name="formation_pathways")
    op.drop_table("formation_pathways")
    op.drop_index("idx_fidelity_tenant_student", table_name="fidelity_scores")
    op.drop_table("fidelity_scores")
    op.drop_index("idx_corrections_submission", table_name="corrections")
    op.drop_index("idx_corrections_created", table_name="corrections")
    op.drop_table("corrections")
    op.drop_index("idx_bluebook_subs_tenant", table_name="bluebook_submissions")
    op.drop_table("bluebook_submissions")
    op.drop_index("idx_bluebook_exams_tenant", table_name="bluebook_exams")
    op.drop_table("bluebook_exams")
    op.drop_index("idx_bluebook_courses_tenant", table_name="bluebook_courses")
    op.drop_table("bluebook_courses")
    op.drop_index("idx_baseline_requests_status", table_name="baseline_requests")
    op.drop_table("baseline_requests")
    op.drop_index("idx_ai_likelihood_tenant_student", table_name="ai_likelihood_scores")
    op.drop_table("ai_likelihood_scores")
    op.drop_index("idx_tuned_thresholds_created", table_name="tuned_thresholds_v2")
    op.drop_table("tuned_thresholds_v2")
    op.drop_index("idx_tenants_environment", table_name="tenants")
    op.drop_table("tenants")
    op.drop_index("idx_calibration_started", table_name="calibration_runs")
    op.drop_table("calibration_runs")
    op.drop_index("idx_audit_student", table_name="audit_log")
    op.drop_index("idx_audit_action", table_name="audit_log")
    op.drop_table("audit_log")
    # ### end Alembic commands ###
