"""park sessions and beats

The QR phone-park proctoring-deterrence surface (T8): two tables modeled in
original/db/models/live.py as ``ParkSession``/``ParkBeat``, and created in
parallel by the SQLite ladder in original/store.py:_get_conn().

PRIVACY — these tables are deliberately anaemic (docs/STUDENT_DISCLOSURE.md).
They carry an opaque ``park_token``, the professor's ``exam_session_id``, a
free-text ``student_hint`` the student types on their own phone, UTC
timestamps, and a JSON list of state transitions. There is NO IP address, NO
user-agent, NO location, NO device fingerprint, and NO roster identifier —
note the absence of the ``(tenant_id, student_id)`` composite every other
student-scoped table here carries. ``park_sessions.tenant_id`` scopes a
professor's reads to their own institution; it identifies a school, not a
person. Rows are purged after 24h by ``Repository.park_purge``.

``park_beats`` deliberately has no FK to ``park_sessions.park_token``: the
SQLite store runs with FK enforcement off, so an FK here would make the two
backends disagree. Orphans are removed explicitly by park_open (on token
rotation), park_delete, and park_purge — the same "no invented FKs" posture
the live baseline took.

Revision ID: 3f695550f43e
Revises: 20128da16c79
Create Date: 2026-07-25 00:16:34.958799

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3f695550f43e"
down_revision: str | None = "20128da16c79"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "park_beats",
        sa.Column("park_token", sa.Text(), nullable=False),
        sa.Column("student_hint", sa.Text(), nullable=False),
        sa.Column("state", sa.Text(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "transitions_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("park_token", "student_hint", name=op.f("pk_park_beats")),
    )
    op.create_table(
        "park_sessions",
        sa.Column("exam_session_id", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("park_token", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.tenant_id"], name=op.f("fk_park_sessions_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("exam_session_id", name=op.f("pk_park_sessions")),
        sa.UniqueConstraint("park_token", name=op.f("uq_park_sessions_park_token")),
    )
    op.create_index("idx_park_sessions_created", "park_sessions", ["created_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_park_sessions_created", table_name="park_sessions")
    op.drop_table("park_sessions")
    op.drop_table("park_beats")
    # ### end Alembic commands ###
