#!/usr/bin/env python3
"""
update_score_snapshot.py — regenerate the committed scoring snapshots.

`tests/config/test_flag_byte_identity.py` diffs the default scoring output
against two committed baselines:

  tests/snapshots/score_default.json      quantum.scoring.score() under
                                          ScoringConfig() (every flag at its
                                          documented default)
  tests/snapshots/score_default_api.json  POST /students/{id}/score for the
                                          same fixed profile with every flag
                                          env var unset

so a change to default output becomes a reviewed diff in the commit rather
than a silent drift. Every flag arm in that file is measured against these
two files, which is why they are regenerated by a named script and never by
hand.

Serialisation, the fixed profile and the API normalisation all come from the
test module itself (`serialise`, `build_unit_snapshot_text`,
`build_api_snapshot_text`) rather than being reimplemented here, so the
script and the test can never quietly disagree about how the same output is
written down. Floats are emitted at full `repr` precision — a rounded
snapshot would hide exactly the 1-ULP regressions this matrix exists to
catch.

That sharing is load-bearing for the feature backends too, not just for
serialisation. `build_api_snapshot_text` enters `api_harness()`, which
enters `force_tfidf_tier10()`, so the snapshot this script writes is
generated on tier 10's deterministic TF-IDF backend even on a machine
where `sentence_transformers` is installed and would otherwise be picked
(it produces different floats, and CI and the pilot lockset cannot
reproduce them). Keep that pin inside the shared harness: if it is ever
duplicated here as a separate direct attribute set, the script and the
fixtures become two seams that have to be kept in lockstep by hand, and
the first regeneration from a machine where they disagree commits a
snapshot the tests reject. `test_api_arms_use_the_tfidf_tier10_backend`
is what catches that.

Usage:
    .venv/bin/python scripts/update_score_snapshot.py
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent


def main() -> None:
    sys.path.insert(0, str(REPO_ROOT))
    from tests.config.test_flag_byte_identity import (
        API_SNAPSHOT_PATH,
        UNIT_SNAPSHOT_PATH,
        build_api_snapshot_text,
        build_unit_snapshot_text,
    )

    for path, builder in (
        (UNIT_SNAPSHOT_PATH, build_unit_snapshot_text),
        (API_SNAPSHOT_PATH, build_api_snapshot_text),
    ):
        text = builder()
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8", newline="\n")
        print(f"Wrote {path.relative_to(REPO_ROOT)} ({len(text)} bytes)")


if __name__ == "__main__":
    main()
